from . import resignation_letter
from . import covering_letter
from . import covering_letter
from . import form2_word
from . import er1_word
from . import mw_register_excel
from . import formd_excel
from . import leave_application
from . import form15G
from . import form_11_newsept_17
from . import recruitment
from . import ESIC_form
from . import pf_form
from . import hr_salary_attachment_excel
from . import hr_custom_form_staff_loan
from . import labour_colony_agreement
from . import nomination_form
from . import appointment_letter
